spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: StudentDB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp

server:
  port: 8085
  servlet:
    context-path: /AdmissionApp
